import Nav from "./components/nav";
import "../styles/globals.css";
import {nunito} from '../fonts/fonts';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es-MX">
            <body className={nunito.className}>
                <header>
                    <Nav />
                </header>
                {children}
            </body>
        </html>
    );
}
