import Nav from "./components/nav";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es-MX">
            <body className={inter.className}>
                <header>
                    <Nav />
                </header>
                {children}
            </body>
        </html>
    );
}
