
//* Next auth imports
import Provider from "./components/provider";

//* Styles
import "../styles/styles.css";

//* Fontawesome imports
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';

library.add(fas, far);

//* Font
import { nunito } from "@/fonts/fonts";

// * Components
import Nav from "./components/nav";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es-MX">
            <body className={nunito.className}>
                <Provider>
                    <header>
                        <Nav />
                    </header>
                    {children}
                </Provider>
            </body>
        </html>
    );
}
